author = F. Di Iorio, S. Fachin, A. Tarassow, Riccardo "Jack" Lucchetti
email = stefano.fachin@uniroma1.it
version = 1.4
date = 2023-01-28
description = Stationary bootstrap resampling of time series
tags = C12 C15 C22 C32
min-version = 2020a
public = SB
gui-main = SB
gui-help = SB_help.txt
data-requirement = no-data-ok
help = SB_help.txt
sample-script = SB_sample.inp
